name: dcf_primitives
description: "Core UI primitives for the DCFlight framework"
version: 0.0.1
homepage: https://github.com/squirelboy360/dcflight
repository: https://github.com/squirelboy360/dcflight

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dcflight:
    path: ../dcflight

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DcfPrimitives


