name: dcf_go
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
# DCFlight is a framework that provides a util to diverge from the original flutter framework to the DCFlight framework. With little to no abstsraction over the native layer and definately not the flutter layer.
# So we still have flutter sdk if you want to use it or even mix and match with the DCFlight framework. 
  flutter:
    sdk: flutter

  dcflight:
    path: ../../dcflight

  dcf_primitives:
    path: ../../dcf_primitives

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
# uses material design by default if you decide to use the `flutterViewAdapter component`
  uses-material-design: true

  