name: dcf_go
description: "A new DCFlight project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  dcflight:
    path: ../../dcflight

  dcf_primitives:
    path: ../../dcf_primitives

  dcf_router:
    path: ../../dcf_router

dev_dependencies:
  flutter_test:
    sdk: flutter



# Assets go here
flutter:
  assets:
    - assets/